
HARVARD_APARATUS_DESCRIPTION = "USB Serial Device"
HARVARD_APARATUS_HARDWARE_ID = "USB VID:PID=1FE9:1103 SER=D402275 LOCATION=1-2"

WEBCAM_DESCRIPTION = ""
WEBCAM_HARDWARE_ID = ""

PRESSURE_DESCRIPTION = ""
PRESSURE_HARDWARE_ID = ""